Repository team-naming-1-hour/sweater-app, pull requests merged in 2022-05, with the labels that each got.

#137 fix/데이터 없을 때 무한로딩 버그 수정(#130)
  lib/pages/home_page.dart
  lib/providers/coordi_provider.dart
Labels: fix

#136 feat/ 위치 검색을 동까지 가능하도록 json 수정
  assets/saved_location.json
  lib/providers/location_provider.dart
  test/units/location_provider_test.dart
Labels: feat

#139 style/날씨 간격 벌리기(#131)
  lib/widgets/weather_view.dart
  pubspec.yaml
Labels: style

#140 Chore/#132/apply moon image
  lib/api/firestore.dart
  lib/module/decide_weather_icon.dart
Labels: style

#151 fix/ saved_location.json의 오류수정
  assets/saved_location.json
Labels: fix

#161 feature/시간별 클릭시 코디 섹션에 로딩 표현(#159)
  lib/providers/coordi_provider.dart
  lib/widgets/coordi_section.dart
Labels: feat

#166 fix/ 홈페이지에 스크롤 가능하도록 함 (#154)
  lib/pages/home_page.dart
Labels: fix

#175 Feature/#171/버튼을 없애고 슬라이드를 달았습니다.
  assets/cloth/one_piece/line_one_piece/line_one_piece-mustard.png
  lib/pages/home_page.dart
  lib/widgets/card_container.dart
  lib/widgets/coordi_section.dart
  lib/widgets/weather_view.dart
  pubspec.lock
  pubspec.yaml
Labels: feat

#194 Feature/#149/weather test
  lib/api/fetch_coordi_list.dart
  lib/api/fetch_weather.dart
  lib/module/decide_weather_icon.dart
  lib/module/forecast.dart
  lib/pages/home_page.dart
  lib/providers/coordi_provider.dart
  lib/providers/weather_provider.dart
  lib/widgets/hourly_weather_card.dart
  lib/widgets/hourly_weather_section.dart
  lib/widgets/weather_view.dart
  test/api/fetch_coordi_list_test.dart
  test/api/fetch_weather_test.dart
  test/units/coordi_provider_test.dart
  test/units/weather_provider_test.dart
Labels: feat

#199 feat/ 코디 보러가는 링크 추가(#191)
  lib/widgets/coordi_section.dart
Labels: feat

#203 Feature/#186/make coordi drawer
  lib/main.dart
  lib/my_http_overrides.dart
  test/api/fetch_coordi_list_test.dart
  test/api/fetch_weather_test.dart
  test/units/weather_provider_test.dart
  test/widgets/manage_location_page_test.dart
Labels: chore

#211 테스트 변경 및 링크 접속 후 앱 재구동시 새로고침되는 버그 수정
  lib/pages/home_page.dart
Labels: chore, fix

#212 Sweather 1.1.0+7
  .github/workflows/main.yml
  README.md
  assets/cloth/one_piece/line_one_piece/line_one_piece-mustard.png
  assets/fonts/icons/SweaterIcons.ttf
  lib/api/fetch_coordi_list.dart
  lib/api/fetch_filter_list.dart
  lib/api/fetch_weather.dart
  lib/main.dart
  lib/module/constitution.dart
  lib/module/coordi.dart
  lib/module/decide_weather_icon.dart
  lib/module/forecast.dart
  lib/my_http_overrides.dart
  lib/pages/constitution_page.dart
  lib/pages/gender_change_page.dart
  lib/pages/home_page.dart
  lib/pages/manage_location_page.dart
  lib/providers/coordi_provider.dart
  lib/providers/user_provider.dart
  lib/providers/weather_provider.dart
  lib/theme/global_theme.dart
  lib/theme/sweater_icons.dart
  lib/widgets/card_container.dart
  lib/widgets/category_tile.dart
  lib/widgets/change_coordi_button.dart
  lib/widgets/check_menu.dart
  lib/widgets/coordi_section.dart
  lib/widgets/filter_drawer.dart
  lib/widgets/hourly_weather_card.dart
  lib/widgets/hourly_weather_section.dart
  lib/widgets/weather_view.dart
  pubspec.lock
  pubspec.yaml
  test/api/fetch_coordi_list_test.dart
  test/api/fetch_weather_test.dart
  test/units/coordi_provider_test.dart
  test/units/coordi_test.dart
  test/units/weather_provider_test.dart
  test/widgets/manage_location_page_test.dart
Labels: feat

#213 선택된 타일에 bold 적용되도록 수정
  lib/widgets/check_menu.dart
Labels: fix

#214 Sweather 1.1.0
  lib/widgets/check_menu.dart
Labels: fix

#216 fix/post 요청에 headers 추가
  lib/api/fetch_filter_list.dart
Labels: fix

#217 추천 카테고리 목록 post에 header 추가
  lib/api/fetch_filter_list.dart
Labels: feat

#232 style/코디에 스타일 정보 추가(#221)
  lib/widgets/coordi_section.dart
Labels: feat, style

#234 feature/No-data UI 변경(#222)
  assets/no-data-black.png
  assets/no-data-white.png
  lib/widgets/coordi_section.dart
Labels: feat

#236 Feature/#223/add getting more coordi button
  lib/widgets/coordi_section.dart
Labels: feat

#237 fix/필터 적용 안하고 닫았을 때 이전에 적용된 필터로 되돌리기(#231)
  lib/providers/coordi_provider.dart
  lib/widgets/category_tile.dart
  lib/widgets/coordi_section.dart
  lib/widgets/filter_drawer.dart
Labels: fix

#241 sweather 1.2.0+10
  lib/pages/manage_location_page.dart
  pubspec.yaml
Labels: fix

#242 Sweather 1.2.2+11
  assets/guide/delete_guide.png
  pubspec.yaml
Labels: chore
